# Generated by Django 6.0.4 on 2026-04-26 22:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('panier', 'Panier'), ('en_attente', 'En attente'), ('confirmee', 'ConfirmÃ©e'), ('en_preparation', 'En prÃ©paration'), ('livree', 'LivrÃ©e'), ('annulee', 'AnnulÃ©e')], default='panier', max_length=20)),
                ('total', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('adresse_livraison', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
    ]
