# Generated by Django 6.0.4 on 2026-04-26 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_initial'),
        ('menu', '0001_initial'),
        ('plat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecommande',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='plat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plat.plat'),
        ),
    ]
