# Generated by Django 6.0.4 on 2026-04-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id_plat', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('calorie', models.FloatField(help_text='Calories en kcal')),
                ('proteine', models.FloatField(help_text='ProtÃ©ines en grammes')),
                ('glucides', models.FloatField(default=0, help_text='Glucides en grammes')),
                ('lipides', models.FloatField(default=0, help_text='Lipides en grammes')),
                ('fibres', models.FloatField(default=0, help_text='Fibres en grammes')),
                ('prix', models.DecimalField(decimal_places=3, max_digits=10)),
                ('est_disponible', models.BooleanField(default=True)),
                ('isNew', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plats/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
