# Generated by Django 6.0.2 on 2026-05-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_actif', models.BooleanField(default=True)),
                ('diet_category', models.CharField(blank=True, choices=[('high-protein', 'High Protein'), ('low-carb', 'Low Carb'), ('vegan', 'Vegan'), ('gluten-free', 'Sans Gluten'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plats', models.ManyToManyField(related_name='menus', to='plat.plat')),
            ],
        ),
    ]
