# Generated by Django 6.0.2 on 2026-05-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilNutritionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('taille', models.DecimalField(decimal_places=2, help_text='Taille en cm', max_digits=5)),
                ('poids', models.DecimalField(decimal_places=2, help_text='Poids en kg', max_digits=5)),
                ('sexe', models.CharField(blank=True, choices=[('homme', 'Homme'), ('femme', 'Femme')], max_length=10)),
                ('allergies', models.TextField(blank=True, help_text='Allergies alimentaires')),
                ('objectif', models.CharField(choices=[('perte_poids', 'Perte de poids'), ('maintien', 'Maintien'), ('prise_muscle', 'Prise de muscle'), ('performance', 'Performance sportive')], max_length=20)),
                ('restrictions_alimentaires', models.TextField(blank=True)),
                ('niveau_activite', models.CharField(choices=[('sedentaire', 'SÃ©dentaire'), ('leger', 'LÃ©gÃ¨rement actif'), ('modere', 'ModÃ©rÃ©ment actif'), ('actif', 'TrÃ¨s actif'), ('extremement_actif', 'ExtrÃªmement actif')], default='modere', max_length=20)),
                ('donnees_sante_sensibles', models.BooleanField(default=False, help_text='Autorisation de traiter les données de santé sensibles')),
                ('learning_collectif', models.BooleanField(default=False, help_text="Autorisation de participer à l'apprentissage collectif")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
