# Generated by Django 6.0.4 on 2026-05-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='n8n_basic_auth_password',
            field=models.CharField(blank=True, help_text='Mot de passe Basic Auth spécifique pour les appels N8N', max_length=255, null=True),
        ),
    ]
