# Generated by Django 6.0.4 on 2026-04-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id_plat', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('calorie', models.FloatField(help_text='Calories en kcal')),
                ('proteine', models.FloatField(help_text='ProtÃ©ines en grammes')),
                ('glucides', models.FloatField(default=0, help_text='Glucides en grammes')),
                ('lipides', models.FloatField(default=0, help_text='Lipides en grammes')),
                ('fibres', models.FloatField(default=0, help_text='Fibres en grammes')),
                ('prix', models.DecimalField(decimal_places=3, max_digits=10)),
                ('est_disponible', models.BooleanField(default=True)),
                ('isNew', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plats/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemeIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Nutrition AI', max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_actif', models.BooleanField(default=True)),
                ('diet_category', models.CharField(blank=True, choices=[('high-protein', 'High Protein'), ('low-carb', 'Low Carb'), ('vegan', 'Vegan'), ('gluten-free', 'Sans Gluten'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plats', models.ManyToManyField(related_name='menus', to='myapp.plat')),
            ],
        ),
    ]
