# Generated by Django 6.0.4 on 2026-04-26 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0003_alter_lignecommande_menu_alter_lignecommande_plat'),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Plat',
        ),
    ]
