# Generated by Django 6.0.4 on 2026-04-27 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_menu_delete_plat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemeIA',
        ),
    ]
