# Generated by Django 6.0.2 on 2026-04-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profilnutritionnel_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='isNew',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
