# Generated by Django 6.0.4 on 2026-04-16 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_plat_isnew_alter_administrateur_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lignecommande',
            options={'verbose_name': 'Ligne de commande', 'verbose_name_plural': 'Lignes de commande'},
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='plat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.plat'),
        ),
        migrations.AddField(
            model_name='menu',
            name='diet_category',
            field=models.CharField(blank=True, choices=[('high-protein', 'High Protein'), ('low-carb', 'Low Carb'), ('vegan', 'Vegan'), ('gluten-free', 'Sans Gluten'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.menu'),
        ),
    ]
