# Generated by Django 6.0.2 on 2026-04-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_lignecommande_options_lignecommande_plat_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompositionMenu',
        ),
    ]
