# Generated by Django 6.0.4 on 2026-04-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_compositionmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('panier', 'Panier'), ('en_attente', 'En attente'), ('confirmee', 'ConfirmÃ©e'), ('en_preparation', 'En prÃ©paration'), ('livree', 'LivrÃ©e'), ('annulee', 'AnnulÃ©e')], default='panier', max_length=20),
        ),
        migrations.AlterField(
            model_name='plat',
            name='proteine',
            field=models.FloatField(help_text='ProtÃ©ines en grammes'),
        ),
        migrations.AlterField(
            model_name='profilnutritionnel',
            name='niveau_activite',
            field=models.CharField(choices=[('sedentaire', 'SÃ©dentaire'), ('leger', 'LÃ©gÃ¨rement actif'), ('modere', 'ModÃ©rÃ©ment actif'), ('actif', 'TrÃ¨s actif'), ('extremement_actif', 'ExtrÃªmement actif')], default='modere', max_length=20),
        ),
    ]
