# Generated by Django 6.0.4 on 2026-04-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_commande_statut_alter_plat_proteine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilnutritionnel',
            name='donnees_sante_sensibles',
            field=models.BooleanField(default=False, help_text='Autorisation de traiter les données de santé sensibles'),
        ),
        migrations.AddField(
            model_name='profilnutritionnel',
            name='learning_collectif',
            field=models.BooleanField(default=False, help_text="Autorisation de participer à l'apprentissage collectif"),
        ),
    ]
